build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  script:
    - apk add nodejs npm git qemu-img libvirt-daemon cdrkit coreutils bash grep util-linux
    - git clone https://github.com/ottomatica/slim.git /tmp/slim
    - cd /tmp/slim && npm i && npm link
    - wget https://github.com/mikefarah/yq/releases/download/3.2.1/yq_linux_amd64 -O /bin/yq && chmod +x /bin/yq
    - cd ${CI_PROJECT_DIR}/vm
    - bash fetch-env.sh
    - slim build --no-cache -p kvm -f iso .
    - mv /root/.slim/registry/vm/slim.iso slim.iso
  artifacts:
    paths:
    - vm/slim.iso

deploy:
  image: alpine:latest
  stage: deploy
  script:
    - apk add jq curl bash
    - bash vm/deploy.sh
